spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-db.ch0w4gg2ikrq.ap-northeast-2.rds.amazonaws.com:3306/shopping_db
    username: aws
    password: 1q2w3e4r!!

  mail:
    host: smtp.gmail.com
    port: 465
    address: rjsgmlq33@gmail.com
    username: rjsgmlq33@gmail.com
    password: pcnoepgpxnndrmon
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 78034546940-49v08dugkec670qd53gbib3giur11tv5.apps.googleusercontent.com
            clientSecret: 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
          naver:
            clientId: YlpCzGKUgMkhIupgaoc4
            clientSecret: 76Gvq9JDeR
          kakao:
            clientId: 6119400cbfa3a2c907803ce6ad116626
            clientSecret: YjUVyR6ltgcQs0TI4CsttVjAiVh9DD4o


jwt:
  secret: bko7XOCWiuBqqBoDI0XWThX+PDosGtaRO6qUpj3L38obtCIiPQsfClT52+IZMyaX

